"""add is_active to URL

Revision ID: 2c44261f2c30
Revises: 8a9479d04528
Create Date: 2025-06-25 14:40:24.896207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c44261f2c30'
down_revision: Union[str, Sequence[str], None] = '8a9479d04528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('URL', 'is_active')
    # ### end Alembic commands ###
