"""add count to URl

Revision ID: 8a9479d04528
Revises: c305f94c54c9
Create Date: 2025-06-24 19:18:00.848686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9479d04528'
down_revision: Union[str, Sequence[str], None] = 'c305f94c54c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('URL', 'count')
    # ### end Alembic commands ###
