"""add expire_time in URL

Revision ID: a7f01c465e74
Revises: f22b353f4eb1
Create Date: 2025-06-28 15:08:14.911471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f01c465e74'
down_revision: Union[str, Sequence[str], None] = 'f22b353f4eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL', sa.Column('expire_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('URL', 'expire_time')
    # ### end Alembic commands ###
